spring:
    # H2 ì½˜ì†” ì„¤ì • (ê°€ì¥ ì¤‘ìš”!)
    h2:
        console:
            enabled: true      # ğŸ‘ˆ ì´ê²Œ trueì—¬ì•¼ H2 ì½˜ì†” ê¸°ëŠ¥ì´ ì¼œì§‘ë‹ˆë‹¤.

    # DB ì—°ê²° ì •ë³´ (jpaì™€ ê°™ì€ ë ˆë²¨ì— ìˆì–´ì•¼ í•©ë‹ˆë‹¤)
    datasource:
        url: jdbc:h2:mem:testdb


    # JPA ì„¤ì •
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true